config/routes.rb
TestApp::Application.routes.draw do

  devise_for :users, :path => 'accounts', :path_names => { :sign_in => 'login', :sign_up => 'new', :sign_out => 'logout', :password => 'secret',
                                    :confirmation => 'verification' }, :controllers => { registrations: 'registrations' }

  resources :students do
    resources :messages, except: [:edit, :update]
  end

  resources :users

  root 'home_pages#home'
  
  match '/help', to: 'home_pages#help', via: 'get'
  match '/about', to: 'home_pages#about', via: 'get'

  
  

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :student
  has_many :attachments

  belongs_to :user

  validates_presence_of :title, :content

  accepts_nested_attributes_for :attachments, :reject_if => :all_blank, :allow_destroy => true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_student
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = @student.messages.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = @student.messages.new
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = @student.messages.new(message_params)
    @message.user_id = current_user.id

    respond_to do |format|
      if @message.save
        format.html { redirect_to [@student, @message], notice: 'Message was successfully created.' }
        format.json { render action: 'show', status: :created, location: @message }
      else
        format.html { render action: 'new' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to student_messages_url(@student) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = @student.messages.find(params[:id])
    end

    def set_student
      @student = Student.find(params[:student_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:title, :content, attachments_attributes: [:file])
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_attachment_fields.html.erb
<div class="nested-fields">
  <%= f.file_field :file %>
  <%= link_to_remove_association "remove", f %>
</div>

app/views/messages/_form.html.erb
<%= form_for([@student, @message]) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div id = 'attachments'>
    <%= f.fields_for :attachments do |attachment| %>
        <%= render 'attachment_fields', :f => attachment %>
    <% end %>
    <div class= 'links pull-right'>
        <%= link_to_add_association 'Add Attachment', f, :attachments %>
    </div>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1><%= @student.name %>'s messages</h1>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th width = "144"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.title %></td>
        <td><%= message.content %></td>
        <td><%= link_to 'Show', student_message_path(@student, message), class: 'btn btn-xs' %>
        <%= link_to 'Destroy',student_message_path(@student, message), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_student_message_path(@student) %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', student_path(@student) %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= link_to @message.student.name, @message.student %>
</p>

<p>
  <strong>Title:</strong>
  <%= @message.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>
<p>
  <strong>Attachments:</strong>
  <ul>
  <% @message.attachments.each do |attachment| %>
    <li><%=  link_to attachment.file_file_name, attachment.file.url %></li>
  <% end %>
  </ul>
</p>

<%= link_to 'Back', student_messages_path(@message.student) %>