config/routes.rb
TestApp::Application.routes.draw do

  devise_for :users, :path => 'accounts', :path_names => { :sign_in => 'login', :sign_up => 'new', :sign_out => 'logout', :password => 'secret',
                                    :confirmation => 'verification' }, :controllers => { registrations: 'registrations' }

  resources :students do
    resources :messages, except: [:edit, :update]
  end

  resources :users

  root 'home_pages#home'
  
  match '/help', to: 'home_pages#help', via: 'get'
  match '/about', to: 'home_pages#about', via: 'get'

  
  

end

app/models/student.rb
class Student < ActiveRecord::Base
  before_save{self.email=email.downcase}

  validates :name, length:{maximum: 50}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
            uniqueness: {case_sensitive: false}

  validates :name, :address, :state, :country, :phone, :zip, :city,
            presence: true

  has_many :messages

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @search = Student.search(params[:q])
    @students = @search.result
  end


  # GET /students/1
  # GET /students/1.json
  def show
    @student = Student.find(params[:id])
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render action: 'show', status: :created, location: @student }
      else
        format.html { render action: 'new' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :address, :state, :country, :zip, :city, :phone, :email)
    end

    def signed_in_user
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<div class="row">
  <div class="span6 offset3">

<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %><br>
  </div>
  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %><br>
  </div>
  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %><br>
  </div>
  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %><br>
  </div>
  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %><br>
  </div>
  <div class="field">
    <%= f.label :zip %>
    <%= f.text_field :zip %><br>
  </div>
  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %><br>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


</div>
</div>

app/views/students/edit.html.erb
<h3>Please update the information</h3>

<%= render 'form' %>

<!-- <%= link_to 'Show', @student,class: "btn btn-large btn-info" %> | -->
<%= link_to 'Back', students_path, class: "btn btn-sm btn-info" %>  

app/views/students/index.html.erb
<div class="pull-right">
  <%= link_to 'Add a Student', new_student_path, class: "btn btn-large btn-success" %>
</div>

<% provide(:title, 'All students') %>
<h1>Students</h1>


<%= search_form_for @search do |f| %>
    <%= f.text_field :name_or_address_or_city_or_state_or_country_or_zip_or_phone_or_email_cont, placeholder: 'Name, address, city, state, country, phone, email' %>
    <%= f.submit "Search", class: 'btn' %>
<% end %>

<table class="table table-striped table-bordered table-condensed">
  <thead>
   <tr>
    <th><%= sort_link(@search, :name,"Name") %></th>
    <th><%= sort_link(@search, :address,"Address") %></th>
    <th><%= sort_link(@search, :city,"City") %></th>
    <th><%= sort_link(@search, :state,"State") %></th>
    <th><%= sort_link(@search, :country,"Country") %></th>
    <th><%= sort_link(@search, :zip,"Zip") %></th>
    <th><%= sort_link(@search, :phone,"Phone") %></th>
    <th><%= sort_link(@search, :email,"Email") %></th>

    <th width="188"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.address %></td>
        <td><%= student.city %></td>
        <td><%= student.state %></td>
        <td><%= student.country %></td>
        <td><%= student.zip %></td>
        <td><%= student.phone %></td>
        <td><%= link_to student.email, new_student_message_path(student) %></td>
        <td>
          <%= link_to 'Show', student, class: 'btn btn-xs' %>
          <%= link_to 'Edit', edit_student_path(student), class: 'btn btn-xs btn-info' %>
          <%= link_to 'Delete', student, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/students/new.html.erb
<% provide(:title, 'Add Student') %>
<h1>Add a Student</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@student) do |f| %>
    <%= render 'shared/error_students' %>

      
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  
    <%= f.label :address %><br>
    <%= f.text_field :address %>

    <%= f.label :city %><br>
    <%= f.text_field :city %>
  
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  
    <%= f.label :email %><br>
    <%= f.text_field :email %>
    
    <div class="pull-right">
      <%= f.submit "Submit", class: "btn btn-large btn-info" %>
      <%= link_to 'Cancel', students_path, class: "btn btn-large btn-info"  %>
    </div>
    <% end %>
  </div>
</div>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @student.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @student.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @student.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @student.country %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @student.zip %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @student.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>