config/routes.rb
TestApp::Application.routes.draw do

  devise_for :users, :path => 'accounts', :path_names => { :sign_in => 'login', :sign_up => 'new', :sign_out => 'logout', :password => 'secret',
                                    :confirmation => 'verification' }, :controllers => { registrations: 'registrations' }

  resources :students do
    resources :messages, except: [:edit, :update]
  end

  resources :users

  root 'home_pages#home'
  
  match '/help', to: 'home_pages#help', via: 'get'
  match '/about', to: 'home_pages#about', via: 'get'

  
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  
  <nav>
    <ul>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "About Developers",   about_path %></li>
      
      
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Giron Brazilian Jiu Jitsu", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          
          
          <% if current_user.present? %>
            <li><%= link_to "Students", students_path %></li>

            <% if current_user.admin? %>
            <li><%= link_to "Users", users_path %></li>
            <% end %>
          
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.name %> <b class="caret"></b>
              </a>
          
              <ul class="dropdown-menu">

                <li><%= link_to "Settings", edit_user_registration_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign Out", destroy_user_session_path, method: "delete" %>
                </li>
              </ul>
          
            </li>
          
          <% else %>
            <li><%= link_to "Sign In", new_user_session_path %></li>
          <% end %>
    
        </ul>
      </nav>
    
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>

      <!-- FOR DEBUG PURPOSES -->
      <%= debug(params) if Rails.env.development? %>

    </div>
  

  </body>
</html>